[project]
name = "kinopoisk-bot"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pydantic-settings>=2.7.0",
    "pydantic>=2.10.4",
    "python-telegram-bot>=21.9",
]
