[tool.poetry]
name = "kinopoisk-bot"
version = "0.1.0"
description = ""
authors = ["yan0f <31446439+yan0f@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "kinopoisk_bot"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"
python-telegram-bot = "^13.15"
python-dotenv = "^0.21.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
