[tool.poetry]
name = "kinopoisk-bot"
version = "0.1.0"
description = ""
authors = ["yan0f <31446439+yan0f@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "kinopoisk_bot" }]

[tool.poetry.dependencies]
python = "^3.11"
python-telegram-bot = "21.0.1"
httpx = "0.27.0"
pydantic = "2.6.4"
pydantic-settings = "2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff.format]
quote-style = "single"

[tool.ruff]
line-length = 135
